

CREATE TABLE Events (
	ID int GENERATED ALWAYS AS IDENTITY,
	TITLE text NOT NULL,
	STOP_DATE date NOT NULL,

	PRIMARY KEY (ID), UNIQUE(ID)
);

CREATE TABLE Persons (
	ID int GENERATED ALWAYS AS IDENTITY,
	NAME text NOT NULL,
	EMAIL text,
	CONTACT text,

	PRIMARY KEY (ID), UNIQUE(ID)
);

CREATE TABLE Invitations (
	EventID int NOT NULL,
	PersonID int NOT NULL,
	ID uuid DEFAULT gen_random_uuid(),
	ACCEPTED int DEFAULT -1,
	
	PRIMARY KEY (ID), UNIQUE(ID)
	FOREIGN KEY (EventID) REFERENCES Events(ID) ON DELETE CASCADE,
	FOREIGN KEY (PersonID) REFERENCES Persons(ID) ON DELETE CASCADE,
	UNIQUE(EventID, PersonID)
);

CREATE TABLE Keys (
	ID uuid DEFAULT gen_random_uuid(),
	NAME text,

	PRIMARY KEY (ID), UNIQUE(ID)
);

INSERT INTO Keys (NAME) VALUES ('Me');

DELETE FROM Persons WHERE ID=1;